In [2]:
import numpy as np

In [4]:
M = np.array([[1, 2], [3, 4]])

In [5]:
M * M

array([[ 1,  4],
       [ 9, 16]])

In [7]:
np.dot(M, M)

array([[ 7, 10],
       [15, 22]])

In [8]:
M

array([[1, 2],
       [3, 4]])

In [9]:
import matplotlib

In [ ]:
!pip install matplotlib